"""Send the daily newsletter digest via Gmail SMTP."""

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import pytz


GMAIL_SMTP_HOST = "smtp.gmail.com"
GMAIL_SMTP_PORT = 587


def _build_html(items: list[dict], date_str: str) -> str:
    """Build a clean HTML email body from processed newsletter items."""

    cards = ""
    for item in items:
        url = item.get("url", "")
        source = item.get("source", "Unknown")
        title = item.get("title", "Untitled")
        pub = item.get("published_at", "")
        insights = item.get("insights", "").replace("\n", "<br>")

        link_html = f'<a href="{url}" style="color:#6c47ff;">{url}</a>' if url else ""
        pub_html = f'<span style="color:#888;font-size:12px;">{pub}</span>' if pub else ""

        cards += f"""
        <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;
                    padding:20px;margin-bottom:20px;">
            <div style="font-size:12px;color:#6c47ff;font-weight:600;
                        text-transform:uppercase;letter-spacing:1px;">{source}</div>
            <h2 style="margin:8px 0 4px;font-size:18px;color:#111;">{title}</h2>
            {pub_html}
            {f'<div style="margin-top:4px;">{link_html}</div>' if link_html else ''}
            <hr style="border:none;border-top:1px solid #f0f0f0;margin:12px 0;">
            <div style="font-size:15px;line-height:1.7;color:#333;">{insights}</div>
        </div>
        """

    if not cards:
        cards = """<div style="text-align:center;padding:40px;color:#888;">
            No newsletters found for today. Check your sources in config.yaml.
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:'Helvetica Neue',Arial,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:24px 16px;">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#6c47ff,#a855f7);
                border-radius:12px;padding:28px;margin-bottom:24px;text-align:center;">
      <h1 style="margin:0;color:#fff;font-size:24px;">Daily Newsletter Insights</h1>
      <p style="margin:8px 0 0;color:rgba(255,255,255,0.85);font-size:14px;">{date_str}</p>
    </div>

    <!-- Newsletter Cards -->
    {cards}

    <!-- Footer -->
    <div style="text-align:center;font-size:12px;color:#aaa;margin-top:24px;">
      Generated by your Newsletter Automation &bull; Delivered at 10 AM IST
    </div>
  </div>
</body>
</html>"""


def _build_plain_text(items: list[dict], date_str: str) -> str:
    """Build a plain text fallback for email clients that don't render HTML."""
    lines = [f"Daily Newsletter Insights — {date_str}", "=" * 50, ""]
    for item in items:
        lines.append(f"[{item.get('source', 'Unknown')}]")
        lines.append(f"Title: {item.get('title', 'Untitled')}")
        if item.get("url"):
            lines.append(f"URL: {item['url']}")
        if item.get("published_at"):
            lines.append(f"Published: {item['published_at']}")
        lines.append("")
        lines.append(item.get("insights", "No insights available."))
        lines.append("")
        lines.append("-" * 50)
        lines.append("")
    return "\n".join(lines)


def send_digest(items: list[dict], sender_email: str, recipient_email: str) -> None:
    """
    Send the daily digest email via Gmail SMTP.

    Args:
        items: Processed newsletter items (with 'insights' field)
        sender_email: Gmail address used to send
        recipient_email: Destination email address
    """
    app_password = os.getenv("GMAIL_APP_PASSWORD", "")
    if not app_password:
        raise EnvironmentError("GMAIL_APP_PASSWORD environment variable is not set.")

    ist = pytz.timezone("Asia/Kolkata")
    now_ist = datetime.now(ist)
    date_str = now_ist.strftime("%A, %d %B %Y")

    subject = f"Your Newsletter Digest — {date_str}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = recipient_email

    msg.attach(MIMEText(_build_plain_text(items, date_str), "plain"))
    msg.attach(MIMEText(_build_html(items, date_str), "html"))

    print(f"[sender] Connecting to Gmail SMTP...")
    with smtplib.SMTP(GMAIL_SMTP_HOST, GMAIL_SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(sender_email, app_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())

    print(f"[sender] Digest sent to {recipient_email} — {len(items)} items.")
